# Generated by Django 2.1.2 on 2018-11-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20181026_1500'),
        ('carts', '0002_cart_subtotal'),
    ]

    operations = [
    ]
