# Generated by Django 2.1.2 on 2018-11-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181027_0146'),
        ('products', '0004_auto_20170901_2159'),
        ('products', '0002_product_price'),
        ('products', '0009_product_timestamp'),
    ]

    operations = [
    ]
