# Generated by Django 2.1.2 on 2018-11-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170928_2052'),
        ('billing', '0002_auto_20181027_0149'),
    ]

    operations = [
    ]
