# Generated by Django 2.1.2 on 2018-11-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectviewed',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Object viewed', 'verbose_name_plural': 'Objects viewed'},
        ),
    ]
